experiment:
    id: TARL

##Data
data:
    data_dir: './Datasets/SemanticKITTI'
    split: 'train'
    dataloader: 'TemporalSemKITTI'
    train: [ '00', '01', '02', '03', '04', '05', '06', '07', '09', '10' ]
    validation: [ '08' ]
    test: ['11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21']
    intensity: True
    percentage: '1.0'

##Training
train:
    resolution: 0.05
    num_points: 40000
    scan_window: 12
    pre_train: True
    n_gpus: 1
    num_workers: 8
    max_epoch: 200
    lr: 0.0002
    decay_lr: 1.0e-4
    sample_points: 300
    tau: 0.1
    momentum: 0.999
    batch_size: 8
    visualize_attn: False

##Network
model:
    out_dim: 96

